# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/aitrace.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import model_pb2 as proto_dot_model__pb2
from proto import sampler_pb2 as proto_dot_sampler__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/aitrace.proto',
  package='AITrace',
  syntax='proto2',
  serialized_options=_b('\n\013com.AITraceB\014AITraceProtoP\001Z\tAITracepb'),
  serialized_pb=_b('\n\x13proto/aitrace.proto\x12\x07\x41ITrace\x1a\x11proto/model.proto\x1a\x13proto/sampler.proto\"a\n\x08Instance\x12\x13\n\x0bworking_dir\x18\x01 \x01(\t\x12\x1d\n\x05model\x18\x03 \x01(\x0b\x32\x0e.AITrace.Model\x12!\n\x07sampler\x18\x05 \x01(\x0b\x32\x10.AITrace.Sampler\"0\n\tInstances\x12#\n\x08instance\x18\x01 \x03(\x0b\x32\x11.AITrace.InstanceB(\n\x0b\x63om.AITraceB\x0c\x41ITraceProtoP\x01Z\tAITracepb')
  ,
  dependencies=[proto_dot_model__pb2.DESCRIPTOR,proto_dot_sampler__pb2.DESCRIPTOR,])




_INSTANCE = _descriptor.Descriptor(
  name='Instance',
  full_name='AITrace.Instance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='working_dir', full_name='AITrace.Instance.working_dir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='AITrace.Instance.model', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampler', full_name='AITrace.Instance.sampler', index=2,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=169,
)


_INSTANCES = _descriptor.Descriptor(
  name='Instances',
  full_name='AITrace.Instances',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='instance', full_name='AITrace.Instances.instance', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=219,
)

_INSTANCE.fields_by_name['model'].message_type = proto_dot_model__pb2._MODEL
_INSTANCE.fields_by_name['sampler'].message_type = proto_dot_sampler__pb2._SAMPLER
_INSTANCES.fields_by_name['instance'].message_type = _INSTANCE
DESCRIPTOR.message_types_by_name['Instance'] = _INSTANCE
DESCRIPTOR.message_types_by_name['Instances'] = _INSTANCES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Instance = _reflection.GeneratedProtocolMessageType('Instance', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCE,
  __module__ = 'proto.aitrace_pb2'
  # @@protoc_insertion_point(class_scope:AITrace.Instance)
  ))
_sym_db.RegisterMessage(Instance)

Instances = _reflection.GeneratedProtocolMessageType('Instances', (_message.Message,), dict(
  DESCRIPTOR = _INSTANCES,
  __module__ = 'proto.aitrace_pb2'
  # @@protoc_insertion_point(class_scope:AITrace.Instances)
  ))
_sym_db.RegisterMessage(Instances)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
